name: Build and Release

on:
  workflow_dispatch:
  release:
    types: [ released,prereleased ]


jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [ windows,  linux, darwin ]
        goarch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "${GITHUB_REF}"
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          check-latest: true
      - name: Gen output name
        run: |
          echo "FILENAME=vertigo_${{ matrix.goos }}_${{ matrix.goarch }}" >> ${GITHUB_ENV}
      - name: Rename Windows File
        if: matrix.goos == 'windows'
        run: |
          echo "FILENAME=vertigo_${{ matrix.goos }}_${{ matrix.goarch }}.exe" >> ${GITHUB_ENV}
      - name: BE Build
        run: |
          go build -o ${{ env.FILENAME }}  cmd/server/main.go
          ls -alh
      
      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILENAME }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FILENAME }}
          tag: ${{ github.ref }}
          file_glob: true
